MAX_LINE_LENGTH: 80
INDENT_SIZE: 2

ALONE_KEYWORDS:
  - "definition"
  - "registration"
  - "notation"
  - "theorem"
  - "scheme"
  - "case"
  - "suppose"
  - "hereby"
  - "now"
  - "proof"
  - "environ"
  - "begin"
  - "provided"
  - "existence"
  - "uniqueness"
  - "end"

TOP_OF_BLOSK_TAGS:
  - "begin"
  - "definition"
  - "registration"
  - "notation"
  - "theorem"
  - "scheme"
